# Generated by Django 4.1.4 on 2022-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.png', upload_to='products/'),
            preserve_default=False,
        ),
    ]
